name: Linting

on: [push]

env:
  PUBLIC_SUPABASE_URL: 'https://fake_test_url.supabase.co'
  PUBLIC_SUPABASE_ANON_KEY: 'fake_anon_key'
  PRIVATE_SUPABASE_SERVICE_ROLE: 'fake_service_role'
  PRIVATE_STRIPE_API_KEY: 'fake_strip_api_key'
  PUBLIC_SITE_NAME: 'SaaS Starter Build Test'

jobs:
  lint_and_check:
    name: Lint and Type Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: NPM install
        run: npm ci

      - name: Linting
        run: npm run lint
        continue-on-error: true

      - name: Typechecking
        run: npm run check
        continue-on-error: true